### PR TITLE
Issue templates

### PR DESCRIPTION
**Pull request by rajavishah**
Added 2 Issue Templates, 
1. Bug Reporting
2. New Feature Request

@gnodar01 could be reviewed and merged at your convenience

### CODE REVIEW

**Comment by gnodar01** [comment]
I think for feature request, we can maybe subdivide it up into:
- spec enhancement (e.g. new UI types, etc)
- algorithm request (e.g. my cool dl algo, preferably already dockerized)
- interface request (e.g. streamlit, quorto, etc)
- other

**Comment by rajavishah** [comment]
> I think for feature request, we can maybe subdivide it up into:
> 
> * spec enhancement (e.g. new UI types, etc)
> * algorithm request (e.g. my cool dl algo, preferably already dockerized)
> * interface request (e.g. streamlit, quorto, etc)
> * other

Thankyou for the new idea :)

**Comment by rajavishah** [comment]
How about now @gnodar01 ?

**Comment by gnodar01** [comment]
Is there any way to preview the form? I'm too lazy to fork the repo and run it. Do you have a screenshot?

**Comment by rajavishah** [comment]
> Is there any way to preview the form? I'm too lazy to fork the repo and run it. Do you have a screenshot?

Yeah, lemme see, if I can send you something

**Comment by gnodar01** [comment]
Hmm, i'm thinking a dropdown of "spec enhancement", "new DL algorithm", "new interface", "cli flag". Then let them provide the details in the textbox.

**Comment by rajavishah** [comment]
> Hmm, i'm thinking a dropdown of "spec enhancement", "new DL algorithm", "new interface", "cli flag". Then let them provide the details in the textbox.

Certainly, but with a dropdown, the user can only select one of the four options. If they want to mention additional details, they would need to use the textbox to provide more context. However, it's unlikely that a user would want to request all four types of features at once, so the dropdown should work well for guiding them to specify their main request while allowing for further explanation if needed.

**Comment by gnodar01** [comment]
> Certainly, but with a dropdown, the user can only select one of the four options.

That's fine. If they want two things, make two issues.

**Review by gnodar01 — APPROVED** [review]

**Comment by gnodar01** [comment]
LGTM. Merge when ready!

**Pull request merged**
