### PR TITLE
V0.1 cellpose

### PR DESCRIPTION
**Pull request by rajavishah**
Resolves #18

The Current PR will help us to run gradio interface of cellpose on localmachine, without problem. There are 3 or 4 cli-tags which I removed as of now (for eg. `--save_dir`). It was causing some error. 

### This version will be able to do following this locally: (Run the following commands):
- `chmod +x build_docker.sh`
- `sh build_docker.sh`
- The above both things would help you generate both the docker images and `app.py` file
- And then `cd src/Build/parse` 
- Run `python app.py`
- Everything would work locally

### Now, when you go on the docker-side:
- After executing `chmod +x build_docker.sh` and `sh build_docker.sh`
- Run `docker run -p 8000:8000 --name gradio-container -v hostpath:containerpath gradio-image` you may go to docker and check things in it. (Once, I ran it, it took nearly 40mins to generate ouput of 3 images!)

### The Problems that I need to fix are:
- Volume Mount with docker (Maybe?); but as of now discussed with @bethac07 that we can just do it via fileinputs
- As of now, I have hardcoded `
FROM cellprofiler/runcellpose_no_pretrained:0.1` in `Dockerfile`
- And the files weren't displaying the output files on Interface side. When I hardcode those things about fetching the newly generated files from `input_image_path` I can get those. But I believe every algorithm would have different `tag` for getting the `input_files`  hence, needs to have a thought on that

### CODE REVIEW

**Comment by bethac07** [comment]
Great, thanks! 

A couple of q's / notes

- > here are 3 or 4 cli-tags which I removed as of now (for eg. --save_dir). It was causing some error.

Would be great to document which, and what errors they are making

- As we chatted about in person, I'm pretty sure we don't need both `cli_args` in the `exec_function` section, since we can create that programmatically from the inputs

- > And the files weren't displaying the output files on Interface side. When I hardcode those things about fetching the newly generated files from input_image_path I can get those. But I believe every algorithm would have different tag for getting the input_files hence, needs to have a thought on that

Not 100% certain that I followed this, is the issue "where will the output go, will be different for different programs"? If yes: most tools should have a CLI arg for something like that, we can have a not-exposed-to-the-user-config setting that sets the output folder location, perhaps. Maybe have exposure-of-these-settings-to-the-user be a something set a the section level, we can then have folks specify one or more parameters that the overall app.py file will need (because it needs to know where  the output files will live) but the user shouldn't touch. But if I didn't understand the question correctly, please do clarify.

**Comment by rajavishah** [comment]
> As we chatted about in person, I'm pretty sure we don't need both cli_args in the exec_function section, since we can create that programmatically from the inputs

Sure, I can move around the logic with removing cli_args. And in that case, we need to priorly decide for each algorithm which tags should be by default added to the cli with which default value. And those could be moved in `exec_function.cli_command` or as @bethac07 mentioned a array of inputs which won't be exposed to user via Gradio Interface, but should be added whilst generating `cli_command`

**Comment by bethac07** [comment]
Definitely let's not use `image_path` at all. After chatting in person about unet and nclasses, we won't do those either. I don't see a compelling reason to make a 3D vs a 2D version, but willing to be talked into that (but would generally say 1 app is less work than 2). 

Example img_filter is [here](https://github.com/CellProfiler/tutorials/blob/master/internal_use/docs/source/BeginnerSegmentation/BeginnerSegmentationPlugins.md#only-if-you-are-curious---how-did-we-make-these-label-masks). Add_model will need to be a file upload, I'm sure the image analysts can give you a file!

**Comment by rajavishah** [comment]
> Definitely let's not use `image_path` at all. After chatting in person about unet and nclasses, we won't do those either. I don't see a compelling reason to make a 3D vs a 2D version, but willing to be talked into that (but would generally say 1 app is less work than 2).
> 
> Example img_filter is [here](https://github.com/CellProfiler/tutorials/blob/master/internal_use/docs/source/BeginnerSegmentation/BeginnerSegmentationPlugins.md#only-if-you-are-curious---how-did-we-make-these-label-masks). Add_model will need to be a file upload, I'm sure the image analysts can give you a file!

About 2D and 3D thing, ZeroCostDL4Mic has 2D and 3D notebooks for a specific algorithms. For eg. Stardist and they have only 2D version for Cellpose. Hence, @gnodar01 and I had once a quick conversation like we could make different dockers for 2D and 3D, just referencing my point on that

**Comment by bethac07** [comment]
Ah, I see. My guess is their split on it is because they let you train your own (which will have more-different compute requirements than an inference-only tool), so I think my personal preference remains one-tool-only-for-2D-and-3D, but definitely feel free to run it by the image analysts, still happy to be argued into a different stance

**Review by gnodar01 — APPROVED** [review]

**Pull request merged**
